[build.environment]
    CI="FALSE"
    NODE_OPTIONS = "--max_old_space_size=4096"
    REACT_APP__ENV="PRODUCTION"
    REACT_APP__ISPRODLIVE="FALSE"
    REACT_APP__ETHEREUM_ENDPOINT_LOCAL="http://localhost:8545"
    REACT_APP__ETHEREUM_ENDPOINT_STAGING="https://hh.staging.alice.net"
    REACT_APP__ETHEREUM_ENDPOINT_PRODUCTION="https://eth.alice.net"
    REACT_APP__AToken_CONTRACT_ADDRESS="0x9621718Cc892cA6fF1FC18c5a63c7DDB41f955df"
    REACT_APP__PublicStaking_CONTRACT_ADDRESS="0x093d8C519a20f3943A15EdE0200937Ef7d3f7806"
    REACT_APP__Factory_CONTRACT_ADDRESS="0x77D7c620E3d913AA78a71acffA006fc1Ae178b66"
    REACT_APP__Lockup_CONTRACT_ADDRESS="0x0"
